-- 01_roles.sql
-- Tạo các role dùng cho hệ thống ECM (chạy ở cấp server)

CREATE ROLE ecm_owner
  LOGIN
  PASSWORD 'admin123'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;

CREATE ROLE ecm_migrator
  LOGIN
  PASSWORD 'admin123'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;

CREATE ROLE ecm_app
  LOGIN
  PASSWORD 'admin123'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT
  CONNECTION LIMIT 200;
