version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ecm
      POSTGRES_PASSWORD: ecm
      POSTGRES_DB: ecm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/db-init.sql:/docker-entrypoint-initdb.d/10-init.sql:ro

  minio:
    image: minio/minio:RELEASE.2024-03-30T00-00-00Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
      - ./init/mc-init.sh:/docker-entrypoint.d/mc-init.sh:ro

  redpanda:
    image: redpandadata/redpanda:v23.3.11
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
    ports:
      - "9092:9092"
      - "9644:9644"
    volumes:
      - ./init/topics-init.sh:/docker-entrypoint.d/topics-init.sh:ro

volumes:
  pgdata:
  minio-data:
